const ENTITY_TRANSITIONS = {
  "-500_-480": {
    "Eastern Zhou / Warring States": "Eastern Zhou / Warring States",
    "Yue / Chu States": "Yue / Chu States"
  },
  "-480_-323": {
    "Achaemenid Empire": "Macedonian Empire",
    "Eastern Zhou / Warring States": "Warring States (late)",
    "Yue / Chu States": "Yue / Chu",
    "Magadha": "Nanda Dynasty",
    "Land of Punt": "Garamantes",
    "Olmec Civilization": "Zapotec/Monte Albán",
    "Early Zapotec": "Zapotec/Monte Albán"
  },
  "-323_-200": {
    "Macedonian Empire": "Antigonid Macedonia",
    "Scythia": "Greco-Bactrian Kingdom",
    "Warring States (late)": "Western Han Dynasty",
    "Yue / Chu": "Nanyue",
    "Nanda Dynasty": "Shunga Empire",
    "Maurya Empire": "Shunga Empire",
    "Bactria": "Greco-Bactrian Kingdom",
    "Chavín Culture": "Chavín Culture (declining)",
    "Kingdom of Armenia": "Kingdom of Sophene",
    "Kingdom of Lysimachus": "Kingdom of Pergamon",
    "Athenian Coalition": "Achaean League",
    "Perdiccas": "Atropatene",
    "Laomedon": "Kingdom of Pontus",
    "Etruscans": "Roman Republic",
    "Cyrenaica": "Ptolemaic Kingdom"
  },
  "-200_-150": {
    "Antigonid Macedonia": "Kingdom of Armenia",
    "Nanyue": "Greco-Bactrian Kingdom",
    "Chavín Culture (declining)": "Nazca Culture",
    "Funan (emerging)": "Funan",
    "Atropatene": "Parthian Empire",
    "Aetolian League": "Roman Republic"
  },
  "-150_-44": {
    "Seleucid Empire": "Parthian Empire",
    "Sabaeans": "Himyarite Kingdom",
    "Xiongnu Confederation": "Xiongnu (weakening)",
    "Greco-Bactrian Kingdom": "Indo-Greek Kingdom",
    "Shunga Empire": "Shunga/Kanva India",
    "Kingdom of Pergamon": "Thracian Kingdom",
    "Qataban": "Kingdom of Axum",
    "Kingdom of Numidia": "Roman Republic",
    "Carthage": "Roman Republic",
    "Achaean League": "Roman Republic",
    "Kingdom of Bithynia": "Roman Republic",
    "Paphlagonia": "Roman Republic"
  },
  "-44_-27": {
    "Roman Republic": "Roman Empire",
    "Ptolemaic Kingdom": "Roman Empire",
    "Xiongnu (weakening)": "Xiongnu (split)",
    "Indo-Greek Kingdom": "Indo-Scythian Kingdom",
    "Shunga/Kanva India": "Shunga/Kanva",
    "Kingdom of Gordyene": "Parthian Empire"
  },
  "-27_50": {
    "Yuezhi": "Kushan Empire",
    "Western Han Dynasty": "Eastern Han Dynasty",
    "Xiongnu (split)": [
      "Xiongnu (Northern)",
      "Xiongnu (Southern - Han vassal)"
    ],
    "Indo-Scythian Kingdom": "Kushan Empire",
    "Shunga/Kanva": "Kushan Empire",
    "Funan": "Funan (expanding)",
    "Mauretania": "Roman Empire",
    "Galatia": "Roman Empire",
    "Judea": "Roman Empire",
    "Kingdom of Cappadocia": "Roman Empire",
    "Minaeans": "Himyarite Kingdom",
    "Sabaeans": "Himyarite Kingdom"
  },
  "50_117": {
    "Kingdom of Armenia": "Roman Empire",
    "Kingdom of Pontus": "Roman Empire",
    "Nabataeans": "Roman Empire",
    "Xiongnu (Northern)": "Northern Xiongnu",
    "Xiongnu (Southern - Han vassal)": "Yayoi Japan (proto-states)",
    "Champa (early)": "Champa",
    "Teotihuacan (early)": "Teotihuacan (expanding)",
    "Funan (expanding)": "Funan (peak)",
    "Thracian Kingdom": "Roman Empire",
    "Kingdom of Osroene": "Roman Empire",
    "Kingdom of Sophene": "Roman Empire",
    "Greek City-States": "Roman Empire",
    "Kingdom of Gordyene": "Roman Empire",
    "Kingdom of Adiabene": "Parthian Empire",
    "Kingdom of Commagene": "Roman Empire"
  },
  "117_200": {
    "Eastern Han Dynasty": "Eastern Han Dynasty (late)",
    "Northern Xiongnu": "Satavahana Empire",
    "Kushan Empire": "Kushan Empire (declining)",
    "Yayoi Japan (proto-states)": "Yayoi Japan",
    "Funan (peak)": "Funan",
    "Basketmaker Culture": "Basketmaker III Culture",
    "Teotihuacan (expanding)": "Teotihuacan (metropolis)"
  },
  "200_250": {
    "Parthian Empire": "Sasanian Empire",
    "Kushan Empire": "Western Kushans",
    "Goths": "Gothia",
    "Eastern Han Dynasty (late)": [
      "Wei Kingdom",
      "Shu Kingdom",
      "Wu Kingdom"
    ],
    "Kushan Empire (declining)": "Kushan (remnant)",
    "Satavahana Empire": "Gupta Empire (emerging)",
    "Yayoi Japan": "Yayoi/Early Yamato Japan",
    "Nok Culture": "Garamantes",
    "Hopewell Interaction Sphere": "Hopewell Interaction Sphere (declining)",
    "Funan": "Funan (declining)",
    "Teotihuacan (metropolis)": "Teotihuacan (peak)",
    "Kingdom of Osroene": "Sasanian Empire"
  },
  "250_300": {
    "Indo-Scythians": "Indo-Sasanian Empire",
    "Western Kushans": "Indo-Sasanian Empire",
    "Wei Kingdom": "Western Jin Dynasty",
    "Shu Kingdom": "Western Jin Dynasty",
    "Wu Kingdom": "Western Jin Dynasty",
    "Kushan (remnant)": "Kushan (declining)",
    "Gupta Empire (emerging)": "Gupta Empire",
    "Yayoi/Early Yamato Japan": "Yamato Kingdom",
    "Moche Civilization": "Tiwanaku (early)",
    "Nazca Culture": "Wari (early)",
    "Classic Maya (early)": "Classic Maya",
    "Hopewell Interaction Sphere (declining)": "Hopewell Interaction Sphere (late)",
    "Funan (declining)": "Funan (late)",
    "Teotihuacan (peak)": "Teotihuacan (zenith)",
    "Kingdom of Gordyene": "Lakhmid Kingdom",
    "Sabaeans": "Himyarite Kingdom"
  },
  "300_350": {
    "Kingdom of Kush": [
      "Nobatia",
      "Makuria",
      "Alodia"
    ],
    "Basketmaker III Culture": "Early Pueblo Culture",
    "Western Jin Dynasty": [
      "Eastern Jin Dynasty",
      "Sixteen Kingdoms (Northern China)"
    ],
    "Kushan (declining)": "Gupta Empire",
    "Funan (late)": "Chenla (emerging)",
    "Tiwanaku (early)": "Tiwanaku",
    "Wari (early)": "Wari",
    "Teotihuacan (zenith)": "Teotihuacan (mature)",
    "Hadhramaut": "Himyarite Kingdom",
    "Burgundians": "Huns"
  },
  "350_395": {
    "Roman Empire": [
      "Western Roman Empire",
      "Eastern Roman Empire"
    ],
    "Gothia": "Kidarites",
    "Indo-Sasanian Empire": "Xionites",
    "Sixteen Kingdoms (Northern China)": "Northern Wei (early)",
    "Gupta Empire": "Gupta Empire (peak)",
    "Tiwanaku": "Tiwanaku (expanding)",
    "Wari": "Wari (expanding)",
    "Chenla (emerging)": "Chenla",
    "Teotihuacan (mature)": "Teotihuacan (late)",
    "Cimmerian Bosporus": "Huns",
    "Kingdom of Adiabene": "Sasanian Empire"
  },
  "395_476": {
    "Western Roman Empire": "Visigothic Kingdom",
    "Huns": "Ostrogoths",
    "Vandals": "Vandal Kingdom",
    "Xionites": "White Huns",
    "Eastern Jin Dynasty": "Liu Song Dynasty",
    "Northern Wei (early)": "Northern Wei Dynasty",
    "Gupta Empire (peak)": "Gupta Empire (declining)",
    "Zapotec/Monte Albán": "Zapotec/Monte Albán (late)",
    "Classic Maya": "Late Classic Maya (fractured)",
    "Tiwanaku (expanding)": "Tiwanaku",
    "Teotihuacan (late)": "Teotihuacan (declining)",
    "Lazica": "Eastern Roman Empire",
    "Kidarites": "White Huns",
    "Norse": "Saxons"
  },
  "476_530": {
    "Ostrogoths": "Ostrogothic Kingdom",
    "Ripuarian Franks": "Kingdom of the Franks",
    "Salian Franks": "Kingdom of the Franks",
    "Kingdom of Alamannia": "Kingdom of the Franks",
    "Kingdom of Soissons": "Kingdom of the Franks",
    "Northern Wei Dynasty": "Eastern Wei Dynasty",
    "Liu Song Dynasty": "Liang Dynasty",
    "Gupta Empire (declining)": "Post-Gupta Kingdoms",
    "Yamato Kingdom": "Yamato / Asuka Japan",
    "Chenla": "Chenla",
    "Tiwanaku": "Tiwanaku (peak)",
    "Late Classic Maya (fractured)": "Terminal Classic Maya",
    "Wari (expanding)": "Wari (peak)",
    "Zapotec/Monte Albán (late)": "Zapotec (post-Monte Albán)",
    "Teotihuacan (declining)": "Early Toltec culture",
    "Kingdom of Armenia": "Lazica",
    "Caucasian Albania": "Sasanian Empire"
  },
  "530_570": {
    "Ostrogothic Kingdom": "Eastern Roman Empire",
    "Vandal Kingdom": "Eastern Roman Empire",
    "Anglo-Saxon England": "Kingdom of Mercia",
    "White Huns": "Göktürk Khaganate",
    "Kingdom of the Gepids": "Avar Khaganate",
    "Caucasian Iberia": "Georgia",
    "Himyarite Kingdom": "Eastern Roman Empire",
    "Eastern Wei Dynasty": [
      "Northern Zhou Dynasty",
      "Northern Qi Dynasty"
    ],
    "Liang Dynasty": "Chen Dynasty",
    "Post-Gupta Kingdoms": "Göktürk Khaganate",
    "Yamato / Asuka Japan": "Asuka Japan",
    "Garamantes": "Berber Kingdoms",
    "Tiwanaku (peak)": "Tiwanaku",
    "Wari (peak)": "Wari",
    "Early Toltec culture": "Toltec culture (growing)",
    "Kingdom of Thuringia": "Duchy of Thuringia",
    "Zapotec (post-Monte Albán)": "Zapotec kingdoms",
    "Kingdom of Sussex": "Kingdom of Wessex",
    "Terminal Classic Maya": "Postclassic Maya",
    "Lazica": "Eastern Roman Empire",
    "Burgundian Kingdom": "Kingdom of the Franks"
  },
  "570_632": {
    "Georgia": "Khazaria",
    "Göktürk Khaganate": "Western Göktürks",
    "Kingdom of Wessex": "Kingdom of Northumbria",
    "Kingdom of Deira": "Kingdom of Northumbria",
    "Kingdom of Bernicia": "Kingdom of Northumbria",
    "Kingdom of the Suebi": "Visigothic Kingdom",
    "Northern Zhou Dynasty": "Tang Dynasty",
    "Northern Qi Dynasty": "Tang Dynasty",
    "Chen Dynasty": "Tang Dynasty",
    "Silla Kingdom": "Silla Kingdom (Unified Silla forming)",
    "Srivijaya (early)": "Srivijaya",
    "Wari": "Wari (declining)",
    "Early Pueblo Culture": "Pueblo Culture (expanding)",
    "Toltec culture (growing)": "Toltec Empire (forming)",
    "Postclassic Maya": "Northern Maya (prosperous)",
    "Lombards": "Kingdom of Italy",
    "Turk Shahis": "Karkota Dynasty",
    "Kingdom of East Anglia": "Kingdom of Mercia"
  },
  "632_680": {
    "Eastern Roman Empire": "East Roman Empire",
    "Sasanian Empire": "Umayyad Caliphate",
    "Lakhmid Kingdom": "Umayyad Caliphate",
    "Ghassanids": "Umayyad Caliphate",
    "Nobatia": "Makuria",
    "Western Göktürks": "Turks",
    "Göktürk Khaganate (fragmented)": "Tibetan Empire",
    "Goguryeo Kingdom": "Unified Silla",
    "Baekje Kingdom": "Unified Silla",
    "Silla Kingdom (Unified Silla forming)": "Unified Silla",
    "Asuka Japan": "Nara Japan (emerging)",
    "Harsha's Empire": "Pala Empire",
    "Western Turkic Khaganate": "Umayyad Caliphate",
    "Toltec Empire (forming)": "Toltec Empire",
    "Northern Maya (prosperous)": "Northern Maya",
    "Chenla": "Chenla (reunifying)",
    "Srivijaya": "Srivijaya (expanding)",
    "Wari (declining)": "Wari (contracting)",
    "Karkota Dynasty": "Turk Shahis",
    "Samo's Empire": "Carantania",
    "Brythons": "Breton Kingdoms"
  },
  "680_750": {
    "Visigothic Kingdom": "Umayyad Caliphate",
    "Old Great Bulgaria": "First Bulgarian Empire",
    "Frisia Kingdom": "Kingdom of the Franks",
    "Carantania": "Kingdom of the Franks",
    "Nara Japan (emerging)": "Nara Japan",
    "Umayyad Caliphate": "Abbasid Caliphate",
    "Srivijaya (expanding)": "Srivijaya (zenith)",
    "Dvaravati": "Dvaravati (declining)",
    "Chenla (reunifying)": "Chenla (pre-Angkor)",
    "Toltec Empire": "Toltec Empire (expanding)",
    "Northern Maya": "Northern Maya (zenith)",
    "Tiwanaku": "Tiwanaku (declining)",
    "Pueblo Culture (expanding)": "Pueblo Culture (Chaco rising)",
    "Wari (contracting)": "Chimú Empire (early)",
    "Duchy of Thuringia": "Kingdom of the Franks",
    "Magna Frisia": "Kingdom of the Franks",
    "Kingdom of Lazica": "Umayyad Caliphate"
  },
  "750_850": {
    "Umayyad Caliphate": "Emirate of Córdoba",
    "Kingdom of the Franks": [
      "East Franks",
      "West Franks",
      "Middle Franks"
    ],
    "Kingdom of Italy": "East Franks",
    "Avar Khaganate": "Magyars",
    "Kingdom of Axum": "Ghana Empire",
    "Tang Dynasty": "Tang Dynasty (late/fragmenting)",
    "Tibetan Empire": "Tibetan Empire (declining)",
    "Nara Japan": "Heian Japan",
    "Pala Empire": "Pala Empire (declining)",
    "Rashtrakuta Empire": "Chola Empire",
    "Early Swahili Settlements": "Swahili City-States",
    "Pueblo Culture (Chaco rising)": "Ancestral Puebloans (Chaco era)",
    "Chenla (pre-Angkor)": "Khmer Empire (Angkor founding)",
    "Sailendra Dynasty": "Mataram Kingdom",
    "Pyu City-States": "Pagan Kingdom (early)",
    "Dvaravati (declining)": "Khmer Empire (Angkor founding)",
    "Nanzhao Kingdom": "Nanzhao Kingdom",
    "Toltec Empire (expanding)": "Toltec Empire",
    "Northern Maya (zenith)": "Northern Maya",
    "Chimú Empire (early)": "Chimú Empire",
    "Srivijaya (zenith)": "Srivijaya",
    "Tiwanaku (declining)": "Tiwanaku (contracting)",
    "Idrisid Dynasty": "Idrisids",
    "Fihrids": "Aghlabid Dynasty",
    "Breton Kingdoms": "Kingdom of Wessex",
    "Saxons": "Viking City-States",
    "Bavarians": "Great Moravia",
    "Aquitaine": "West Franks",
    "Dabuyid Dynasty": "Abbasid Caliphate",
    "Turks": "Oghuz Turks",
    "Berber Kingdoms": "Idrisids",
    "Early Aghlabids": "Aghlabid Dynasty"
  },
  "850_900": {
    "Kingdom of Mercia": "Viking City-States",
    "Kingdom of Northumbria": "Viking City-States",
    "Middle Franks": "Kingdom of Lower Burgundy",
    "Turk Shahis": "Samanid Empire",
    "Volga Bulgaria": "Principality of Hungary",
    "Tang Dynasty (late/fragmenting)": "Five Dynasties & Ten Kingdoms",
    "Tibetan Empire (declining)": "Khitan Liao Empire",
    "Nanzhao Kingdom": "Goryeo Kingdom",
    "Unified Silla": "Goryeo Kingdom",
    "Pala Empire (declining)": "Chola Empire",
    "Abbasid Caliphate": "Samanid Empire",
    "Samanid Empire (early)": "Samanid Empire",
    "Early Mississippian Culture": "Mississippian Culture (growing)",
    "Khmer Empire (Angkor founding)": "Khmer Empire (Angkor)",
    "Mataram Kingdom": "Mataram Kingdom",
    "Pagan Kingdom (early)": "Pagan Kingdom (growing)",
    "Srivijaya": "Srivijaya (declining)",
    "Toltec Empire": "Toltec Empire (zenith)",
    "Ancestral Puebloans (Chaco era)": "Ancestral Puebloans (Chaco zenith)",
    "Northern Maya": "Postclassic Maya",
    "Great Moravia": "Principality of Hungary",
    "Tiwanaku (contracting)": "Chimú Empire",
    "Kingdom of Wessex": "Viking City-States"
  },
  "900_1000": {
    "Abbasid Caliphate": "Fatimid Caliphate",
    "East Franks": "Holy Roman Empire",
    "West Franks": "Kingdom of England",
    "Emirate of Córdoba": "Caliphate of Córdoba",
    "Principality of Hungary": "Kingdom of Hungary",
    "Kingdom of Asturias": "Kingdom of León",
    "Viking City-States": "Duchy of Bohemia",
    "Samanid Empire": "Ghaznavid Empire",
    "Five Dynasties & Ten Kingdoms": "Northern Song Dynasty",
    "Idrisid Dynasty": "Fatimid Caliphate",
    "Aghlabids": "Fatimid Caliphate",
    "Djenné-Jeno": "Songhai Empire",
    "Mississippian Culture (growing)": "Mississippian Culture (Cahokia rising)",
    "Khmer Empire (Angkor)": "Khmer Empire (Angkor zenith)",
    "Mataram Kingdom": "Kediri Kingdom",
    "Pagan Kingdom (growing)": "Pagan Kingdom",
    "Srivijaya (declining)": "Srivijaya (contracting)",
    "Dali Kingdom": "Dali Kingdom",
    "Dai Viet (early)": "Dai Viet",
    "Mixtec kingdoms (rising)": "Mixtec kingdoms",
    "Chimú Empire": "Chimú Empire (dominant)",
    "Toltec Empire (zenith)": "Toltec Empire (mature)",
    "Champa": "Champa (under pressure)",
    "Postclassic Maya": "Northern Maya (competing)",
    "Kingdom of Lower Burgundy": "Kingdom of Arles",
    "Tulunids": "Fatimid Caliphate",
    "Aghlabid Dynasty": "Fatimid Caliphate",
    "Idrisids": "Fatimid Caliphate",
    "Bagratid Armenia": "East Roman Empire",
    "Magyars": "Kingdom of Hungary",
    "Khazaria": "Kievan Rus'"
  },
  "1000_1071": {
    "Seljuk Dynasty": "Great Seljuk Empire",
    "Kievan Rus'": "Principality of Pereyaslavl",
    "Kingdom of León": "Kingdom of Galicia",
    "Caliphate of Córdoba": "Almoravid Dynasty",
    "Oghuz Turks": "Great Seljuk Empire",
    "First Bulgarian Empire": "East Roman Empire",
    "Chola Empire": "Chola Empire (declining)",
    "Samanid Empire": "Ghaznavid Empire",
    "Mississippian Culture (Cahokia rising)": "Mississippian Culture (Cahokia at peak)",
    "Khmer Empire (Angkor zenith)": "Khmer Empire (Angkor Wat era)",
    "Pagan Kingdom": "Pagan Kingdom (peak)",
    "Srivijaya (contracting)": "Srivijaya (late)",
    "Dai Viet": "Dai Viet (Lý dynasty)",
    "Northern Maya (competing)": "Northern Maya",
    "Chimú Empire (dominant)": "Chimú Empire",
    "Champa (under pressure)": "Champa",
    "Ancestral Puebloans (Chaco zenith)": "Ancestral Puebloans (Chaco declining)",
    "Toltec Empire (mature)": "Toltec Empire (late)",
    "Ziyadid dynasty": "Najahid Dynasty",
    "Buyid Dynasty": "Great Seljuk Empire",
    "Kingdom of Arles": "Holy Roman Empire",
    "Duchy of Bohemia": "Holy Roman Empire",
    "Georgia": "East Roman Empire"
  },
  "1071_1100": {
    "Kingdom of England": "Norman England",
    "Kingdom of Galicia": "Kingdom of Castile",
    "Khitan Liao Empire": "Jurchen Jin Empire (early)",
    "Mississippian Culture (Cahokia at peak)": "Mississippian Culture (Cahokia dominant)",
    "Ancestral Puebloans (Chaco declining)": "Ancestral Puebloans (Mesa Verde phase)",
    "Khmer Empire (Angkor Wat era)": "Khmer Empire (Angkor)",
    "Pagan Kingdom (peak)": "Pagan Kingdom",
    "Srivijaya (late)": "Srivijaya (remnant)",
    "Dai Viet (Lý dynasty)": "Dai Viet",
    "Champa": "Champa (reduced)",
    "Toltec Empire (late)": "Toltec Empire (transitioning)",
    "Tarascan/Purépecha (early)": "Tarascan Empire",
    "Northern Maya": "Mayapan League",
    "Kingdom of Croatia": "Kingdom of Hungary",
    "Hamdanid Emirates": "Great Seljuk Empire"
  },
  "1100_1200": {
    "Norman England": "Angevin Empire",
    "Fatimid Caliphate": "Ayyubid Sultanate",
    "Almoravid Dynasty": "Almohad Caliphate",
    "Principality of Kiev": "Principality of Halych",
    "Kingdom of Poland": "Duchy of Sandomierz",
    "Northern Song Dynasty": "Southern Song Dynasty",
    "Jurchen Jin Empire (early)": "Jurchen Jin Dynasty",
    "Heian Japan": "Kamakura Japan",
    "Sosso Kingdom": "Almohad Caliphate",
    "Alodia": "Ajuran Sultanate",
    "Toltec Empire (transitioning)": "Aztec Empire (early)",
    "Mayapan League": "Mayapan League (dominant)",
    "Mississippian Culture (Cahokia dominant)": "Mississippian Culture (spreading)",
    "Khmer Empire (Angkor)": "Khmer Empire (post-Jayavarman VII)",
    "Kediri Kingdom": "Singhasari Kingdom",
    "Champa (reduced)": "Champa (vassal)",
    "Pagan Kingdom": "Pagan Kingdom (declining)",
    "Dali Kingdom": "Dali Kingdom",
    "Ancestral Puebloans (Mesa Verde phase)": "Ancestral Puebloans (Mesa Verde)",
    "Dai Viet": "Dai Viet (Trần)",
    "Ghaznavid Empire": "Ghurid Dynasty",
    "Najahid Dynasty": "Ayyubid Sultanate",
    "Duchy of Aquitaine": "Angevin Empire",
    "Principality of Volhynia": "Principality of Halych",
    "Principality of Polotsky": "Principality of Smolensk",
    "Srivijaya (remnant)": "Singhasari Kingdom"
  },
  "1200_1300": {
    "Ayyubid Sultanate": "Mamluk Sultanate",
    "Angevin Empire": "Kingdom of England",
    "Khwarezmid Dynasty": "Golden Horde",
    "Kimek-Kipchak confederation": "Golden Horde",
    "Great Seljuk Empire": "Ilkhanate",
    "Kara-Khitans": "Chagatai Khanate",
    "Holy Roman Empire": "Holy Roman Empire Minor States",
    "Sultanate of Rum": "East Roman Empire",
    "Ghurid Dynasty": "Ilkhanate",
    "Kingdom of Castile": "Crown of Castile",
    "Ghana Empire": "Mali Empire",
    "Kingdom of Denmark": "Kingdom of France",
    "Southern Song Dynasty": "Yuan Dynasty",
    "Jurchen Jin Dynasty": "Yuan Dynasty",
    "Xi Xia Kingdom": "Yuan Dynasty",
    "Mongol Empire (early)": [
      "Yuan Dynasty",
      "Chagatai Khanate",
      "Golden Horde (eastern territories)"
    ],
    "Goryeo Kingdom": "Goryeo Kingdom (Mongol vassal)",
    "Delhi Sultanate (early)": "Delhi Sultanate",
    "Karakhanid Khanate": "Chagatai Khanate",
    "Ghaznavid Empire": "Ilkhanate",
    "Khwarezmid Empire": "Chagatai Khanate",
    "Kara-Khitan (Western Liao)": "Chagatai Khanate",
    "Kanem Empire": "Kanem-Bornu",
    "Mapungubwe": "Great Zimbabwe",
    "Sosso Kingdom": "Mali Empire",
    "Ancestral Puebloans (Mesa Verde)": "Puebloan Migration (to Rio Grande)",
    "Mississippian Culture (spreading)": "Mississippian Culture (post-Cahokia)",
    "Khmer Empire (post-Jayavarman VII)": "Khmer Empire (declining)",
    "Singhasari Kingdom": "Majapahit Empire",
    "Pagan Kingdom (declining)": "Pagan successor states",
    "Sukhothai Kingdom": "Sukhothai Kingdom (late)",
    "Dai Viet (Trần)": "Dai Viet (Trần late)",
    "Dali Kingdom": "Yuan Dynasty",
    "Mayapan League (dominant)": "Mayapan League",
    "Champa (vassal)": "Champa (surviving)",
    "Aztec Empire (early)": "Aztec Empire (expanding)",
    "Principality of Halych": "Galicia-Volhynia",
    "Duchy of Sandomierz": "Grand Duchy of Lithuania",
    "Halych-Volhynia occupation": "Golden Horde",
    "Principality of Chernigov": "Golden Horde",
    "Kingdom of Georgia": "Ilkhanate",
    "Kingdom of León": "Crown of Castile",
    "Principality of Pereyaslavl": "Golden Horde"
  },
  "1300_1350": {
    "Ilkhanate": "Jalayirid Sultanate",
    "Almohad Caliphate": "Marinid Sultanate",
    "Galicia-Volhynia": "Grand Duchy of Lithuania",
    "Principality of Smolensk": "Grand Duchy of Lithuania",
    "Yuan Dynasty": "Ming Dynasty (early)",
    "Chagatai Khanate": "Chagatai Khanate (fragmenting)",
    "Golden Horde (eastern territories)": "Yuan Dynasty (remnant)",
    "Goryeo Kingdom (Mongol vassal)": "Goryeo Kingdom",
    "Kamakura Japan": "Muromachi Japan",
    "Delhi Sultanate": "Delhi Sultanate / Bahmani",
    "Takrur": "Jolof Empire",
    "Puebloan Migration (to Rio Grande)": "Rio Grande Pueblos",
    "Khmer Empire (declining)": "Khmer Empire (late Angkor)",
    "Sukhothai Kingdom (late)": "Ayutthaya Kingdom",
    "Ayutthaya Kingdom (early)": "Ayutthaya Kingdom",
    "Majapahit Empire": "Majapahit Empire (peak)",
    "Pagan successor states": "Ava Kingdom",
    "Dai Viet (Trần late)": "Dai Viet",
    "Mayapan League": "Mayapan League (fragmenting)",
    "Muisca Confederation (early)": "Muisca Confederation",
    "Aztec Empire (expanding)": "Aztec Empire (dominant)",
    "Mississippian Culture (post-Cahokia)": "Mississippian Culture (declining)",
    "Champa (surviving)": "Champa (diminished)",
    "Zayyanid dynasty": "Zayyanid Kingdom",
    "Second Bulgarian Empire": "Ottoman Empire",
    "Principality of Minsk": "Grand Duchy of Lithuania",
    "Marinid Dynasty": "Marinid Sultanate",
    "Zapotec kingdoms": "Mixtec kingdoms",
    "Alodia": "Makuria"
  },
  "1350_1453": {
    "East Roman Empire": "Ottoman Empire",
    "Chagatai Khanate": "Timurid Empire",
    "Jalayirid Sultanate": "Timurid Empire",
    "Kingdom of Hungary": "House of Jagiellon",
    "Kingdom of Bohemia": "House of Habsburg",
    "Grand Duchy of Lithuania": "House of Jagiellon",
    "Makuria": "Makuria Kingdom",
    "Ming Dynasty (early)": "Ming Dynasty",
    "Yuan Dynasty (remnant)": "Timurid Remnants",
    "Chagatai Khanate (fragmenting)": "Timurid Remnants",
    "Goryeo Kingdom": "Joseon Korea",
    "Majapahit Empire": "Majapahit Empire (declining)",
    "Delhi Sultanate / Bahmani": "Delhi Sultanate / Bahmani",
    "Great Zimbabwe": "Mutapa Empire",
    "Aztec Empire (dominant)": "Aztec Empire (Triple Alliance at peak)",
    "Chimú Empire": "Inca Empire (Tawantinsuyu - Maximum Extent)",
    "Inca Empire (early expansion)": "Inca Empire (Tawantinsuyu - Maximum Extent)",
    "Mayapan League (fragmenting)": "Northern Maya (independent cities)",
    "Mississippian Culture (declining)": "Late Mississippian chiefdoms",
    "Khmer Empire (late Angkor)": "Khmer Kingdom (post-Angkor)",
    "Majapahit Empire (peak)": "Majapahit Empire (declining)",
    "Champa (diminished)": "Champa (final)",
    "Dai Viet": "Dai Viet (Lê dynasty)",
    "Zayyanid Kingdom": "Zayyanid dynasty",
    "Chobanids": "Qara Qoyunlu",
    "Germiyanids": "Aq Qoyunlu",
    "Sarbadars": "Timurid Empire",
    "Kartids": "Timurid Empire",
    "Muzaffarids": "Timurid Empire"
  },
  "1453_1492": {
    "Crown of Castile": "Spain",
    "Crown of Aragon": "Spain",
    "Marinid Sultanate": "Wattasid Sultanate",
    "Muromachi Japan": "Ashikaga Japan (Sengoku)",
    "Rasulid Dynasty": "Tahirid Sultanate",
    "House of Habsburg": "Habsburg Domains",
    "House of Jagiellon": "Kingdom of Hungary",
    "Golden Horde": "Great Horde",
    "Timurid Empire": "Timurid Remnants",
    "Majapahit Empire (declining)": "Majapahit (remnant)",
    "Delhi Sultanate / Bahmani": "Delhi Sultanate (Lodi)",
    "Aztec Empire (Triple Alliance at peak)": "Aztec Empire",
    "Inca Empire (Tawantinsuyu - Maximum Extent)": "Inca Empire (Tawantinsuyu)",
    "Northern Maya (independent cities)": "Maya City-States",
    "Khmer Kingdom (post-Angkor)": "Khmer Kingdom",
    "Dai Viet (Lê dynasty)": "Dai Viet",
    "Makuria Kingdom": "Adal Sultanate",
    "Champa (final)": "Dai Viet",
    "Qara Qoyunlu": "Aq Qoyunlu"
  },
  "1492_1520": {
    "Mamluk Sultanate": "Ottoman Empire",
    "Aq Qoyunlu": "Safavid Empire",
    "Timurid Remnants": "Shaybanid Khanate",
    "Habsburg Domains": "Habsburg Domains (Charles V)",
    "Great Horde": "Crimean Khanate",
    "Bahmani Sultanate (declining)": "Deccan Sultanates",
    "Tahirid Sultanate": "Ottoman Empire",
    "Majapahit (remnant)": "Malacca Sultanate",
    "Teutonic Order": "Teutonic Order"
  },
  "1520_1555": {
    "Delhi Sultanate (Lodi)": "Mughal Empire",
    "Aztec Empire": "Spain",
    "Tarascan Empire": "Spain",
    "Mixtec kingdoms": "Spain",
    "Maya City-States": "Spain",
    "Inca Empire (Tawantinsuyu)": "Spain",
    "Late Mississippian chiefdoms": "Late Mississippian chiefdoms",
    "Habsburg Domains (Charles V)": "Habsburg Domains (Charles V)",
    "Teutonic Order": "Poland-Lithuania",
    "Kingdom of Hungary": "Ottoman Empire",
    "Malacca Sultanate": "Kingdom of Portugal",
    "Deccan Sultanates": "Deccan Sultanates",
    "Kilwa Sultanate": "Kingdom of Portugal",
    "Shaybanid Khanate": "Shaybanid Khanate"
  },
  "1555_1600": {
    "Tsardom of Russia": "Tsardom of Russia",
    "Ashikaga Japan (Sengoku)": "Tokugawa Japan",
    "Wattasid Sultanate": "Saadi Sultanate",
    "Vijayanagara Empire": "Deccan Sultanates",
    "Zayyanid dynasty": "Ottoman Empire",
    "Hafsid Dynasty": "Ottoman Empire",
    "Republic of Florence": "Republic of Florence"
  },
  "1600_1648": {
    "Portuguese Empire (under Spain)": "Kingdom of Portugal",
    "Kingdom of England": "English Commonwealth",
    "Ming Dynasty": "Qing Dynasty",
    "Songhai Empire": "Saadi Sultanate",
    "Saadi Sultanate": "Alaouite Sultanate",
    "Khanate of Sibir": "Tsardom of Russia",
    "Nogai Horde": "Tsardom of Russia",
    "Muisca Confederation": "Spain",
    "Duchy of Milan": "Spain",
    "Republic of Florence": "Spain"
  },
  "1648_1700": {
    "English Commonwealth": "Kingdom of England",
    "Alaouite Sultanate": "Alaouite Sultanate",
    "Safavid Empire": "Safavid Empire",
    "Khanate of Bukhara": "Khanate of Bukhara",
    "Tsardom of Russia": "Russian Empire",
    "Khanate of Sibir": "Russian Empire",
    "Deccan Sultanates": "Mughal Empire",
    "Kingdom of Georgia": "Safavid Empire"
  },
  "1700_1763": {
    "Kingdom of England": "Great Britain",
    "Kingdom of Scotland": "Great Britain",
    "Safavid Empire": "Zand Dynasty",
    "Mughal Empire": "Mughal Empire (rump)",
    "Brandenburg-Prussia": "Kingdom of Prussia",
    "Habsburg Austria": "Habsburg Empire",
    "Ayutthaya Kingdom": "Ayutthaya Kingdom",
    "Lan Xang": "Dai Viet",
    "Ajuran Sultanate": "Ethiopian Empire",
    "Hausa City-States": "Kanem-Bornu",
    "Luba Kingdom": "Kingdom of Kongo",
    "Swahili City-States": "Great Britain"
  },
  "1763_1789": {
    "Ayutthaya Kingdom": "Kingdom of Siam",
    "Ava Kingdom": "Konbaung Burma",
    "Zand Dynasty": "Qajar Dynasty",
    "Dai Viet": "Dai Viet",
    "Republic of Venice": "Republic of Venice",
    "Republic of Genoa": "Great Britain"
  },
  "1789_1815": {
    "Kingdom of France": "Kingdom of France (Restoration)",
    "Dutch Republic": "Kingdom of the Netherlands",
    "Habsburg Empire": "Austrian Empire",
    "Holy Roman Empire Minor States": "German Confederation",
    "Kingdom of Prussia": "Kingdom of Prussia",
    "Poland-Lithuania": "Congress Poland",
    "Maratha Empire": "Maratha Empire",
    "Durrani Empire": "Durrani Empire (declining)",
    "Dai Viet": "Nguyen Vietnam",
    "Denmark-Norway": "Kingdom of Denmark",
    "Kingdom of Sweden": "Sweden-Norway",
    "Kingdom of Mysore": "United Kingdom",
    "Mughal Empire (rump)": "Mughal Empire (rump)",
    "Republic of Venice": "Austrian Empire",
    "Khanate of Bukhara": "Khanate of Bukhara"
  },
  "1815_1848": {
    "Kingdom of France (Restoration)": "France (Second Republic)",
    "Austrian Empire": "Austrian Empire",
    "Sikh Empire": "Sikh Empire",
    "Durrani Empire (declining)": "Emirate of Afghanistan",
    "Maratha Empire": "United Kingdom",
    "Egypt (Muhammad Ali)": "Khedivate of Egypt",
    "Kingdom of Sardinia": "Kingdom of Sardinia",
    "Kingdom of Kongo": "Kingdom of Kongo"
  },
  "1848_1867": {
    "France (Second Republic)": "French Empire (Second)",
    "Austrian Empire": "Austria-Hungary",
    "German Confederation": "North German Confederation",
    "Tokugawa Japan": "Tokugawa Japan",
    "Sikh Empire": "United Kingdom",
    "Mughal Empire (rump)": "United Kingdom",
    "Konbaung Burma": "Konbaung Burma",
    "Papal States": "Kingdom of Italy",
    "Kingdom of Sardinia": "Kingdom of Italy"
  },
  "1867_1884": {
    "French Empire (Second)": "French Third Republic",
    "Kingdom of Prussia": "German Empire",
    "North German Confederation": "German Empire",
    "Tokugawa Japan": "Empire of Japan",
    "Kingdom of Italy": "Kingdom of Italy",
    "Zulu Kingdom": null,
    "Konbaung Burma": null,
    "Nguyen Vietnam": "Nguyen Vietnam"
  },
  "1884_1900": {
    "Empire of Brazil": "Republic of Brazil",
    "Argentine Confederation": "Argentine Republic",
    "Nguyen Vietnam": null,
    "Konbaung Burma": null
  },
  "1900_1914": {
    "Sweden-Norway": "Kingdom of Sweden",
    "Principality of Bulgaria": "Kingdom of Bulgaria",
    "Qing Dynasty": "Republic of China",
    "Congo Free State": "Kingdom of Belgium",
    "Joseon Korea": "Empire of Japan",
    "Alaouite Sultanate": "French Third Republic",
    "Khanate of Bukhara": null
  },
  "1914_1920": {
    "Ottoman Empire": "Ottoman Empire (rump)",
    "Austria-Hungary": "Republic of Austria",
    "German Empire": "Weimar Republic",
    "Russian Empire": "Russian SFSR",
    "Kingdom of Serbia": "Kingdom of Serbs, Croats and Slovenes",
    "Kingdom of Montenegro": "Kingdom of Serbs, Croats and Slovenes"
  },
  "1920_1938": {
    "Ottoman Empire (rump)": "Republic of Turkey",
    "Kingdom of Hejaz": "Kingdom of Saudi Arabia",
    "Weimar Republic": "Third Reich (Nazi Germany)",
    "Russian SFSR": "Soviet Union (USSR)",
    "Qajar Dynasty": "Pahlavi Iran",
    "Republic of Austria": null,
    "Kingdom of Serbs, Croats and Slovenes": "Federal Yugoslavia"
  },
  "1938_1945": {
    "Third Reich (Nazi Germany)": "Occupied Germany",
    "Kingdom of Italy": "Kingdom of Italy",
    "Federal Yugoslavia": "Federal Yugoslavia",
    "Principality of Albania": "People's Republic of Albania",
    "Kingdom of Bulgaria": "People's Republic of Bulgaria"
  },
  "1945_1960": {
    "Occupied Germany": "West Germany (FRG)",
    "Occupied Japan": "Japan",
    "Occupied Korea": "South Korea",
    "Kingdom of Hungary": "Hungarian People's Republic",
    "Kingdom of Romania": "Romanian People's Republic",
    "French Fourth Republic": "French Fifth Republic",
    "Emirate of Transjordan": "Kingdom of Jordan",
    "Kingdom of Egypt": "United Arab Republic (Egypt)",
    "Kingdom of Iraq": "Republic of Iraq",
    "Kingdom of Afghanistan": "Kingdom of Afghanistan",
    "Republic of China": "People's Republic of China"
  },
  "1960_1975": {
    "United Arab Republic (Egypt)": "Arab Republic of Egypt",
    "Socialist Ethiopia (Derg)": null,
    "Kingdom of Afghanistan": "Republic of Afghanistan",
    "Republic of Congo (Leopoldville)": "Republic of Zaire",
    "Kingdom of Greece": "Hellenic Republic",
    "Kingdom of Libya": "Kingdom of Libya"
  },
  "1975_1991": {
    "Soviet Union (USSR)": "Russian Federation",
    "West Germany (FRG)": "Federal Republic of Germany",
    "East Germany (GDR)": "Federal Republic of Germany",
    "Pahlavi Iran": "Islamic Republic of Iran",
    "Federal Yugoslavia": "SFR Yugoslavia (dissolving)",
    "Hungarian People's Republic": "Republic of Hungary",
    "Romanian People's Republic": "Romania",
    "People's Republic of Bulgaria": "Republic of Bulgaria",
    "People's Republic of Albania": "Republic of Albania",
    "Socialist Ethiopia (Derg)": "Transitional Government of Ethiopia",
    "Democratic Kampuchea": "State of Cambodia",
    "Republic of Afghanistan": "Republic of Afghanistan",
    "Kingdom of Portugal": "Portuguese Republic"
  },
  "1991_2000": {
    "SFR Yugoslavia (dissolving)": "Federal Republic of Yugoslavia",
    "Czechoslovakia": "Czech Republic",
    "Republic of Zaire": "Democratic Republic of Congo",
    "Transitional Government of Ethiopia": "Federal Democratic Republic of Ethiopia",
    "State of Cambodia": "Kingdom of Cambodia",
    "Republic of Afghanistan": "Islamic Emirate of Afghanistan"
  },
  "2000_2010": {
    "Federal Republic of Yugoslavia": "Republic of Serbia",
    "Great Socialist People's Libyan Arab Jamahiriya": "Great Socialist People's Libyan Arab Jamahiriya",
    "Islamic Emirate of Afghanistan": "Islamic Republic of Afghanistan"
  },
  "2010_2024": {
    "Great Socialist People's Libyan Arab Jamahiriya": "State of Libya",
    "Islamic Republic of Afghanistan": "Islamic Emirate of Afghanistan",
    "Republic of Macedonia": "Republic of North Macedonia"
  }
};
