// ============================================================
// ENTITY TRANSITIONS — maps entity renames, splits, and merges
// between consecutive keyframes
// Format: { "fromName": "toName" } or { "fromName": ["split1", "split2"] }
// ============================================================

const ENTITY_TRANSITIONS = {
  "-500_-480": {
    "Eastern Zhou / Warring States": "Eastern Zhou / Warring States",
    "Yue / Chu States": "Yue / Chu States",
  },
  "-480_-323": {
    "Achaemenid Empire": "Macedonian Empire",
    "Eastern Zhou / Warring States": "Warring States (late)",
    "Yue / Chu States": "Yue / Chu",
    "Magadha": "Nanda Dynasty",
  },
  "-323_-200": {
    "Macedonian Empire": "Antigonid Macedonia",
    "Scythia": "Greco-Bactrian Kingdom",
    "Warring States (late)": "Western Han Dynasty",
    "Yue / Chu": "Nanyue",
    "Nanda Dynasty": "Shunga Empire",
    "Maurya Empire": "Shunga Empire",
  },
  "-200_-150": {
    "Antigonid Macedonia": "Kingdom of Armenia",
    "Nanyue": "Greco-Bactrian Kingdom",
  },
  "-150_-44": {
    "Seleucid Empire": "Parthian Empire",
    "Sabaeans": "Himyarite Kingdom",
    "Xiongnu Confederation": "Xiongnu (weakening)",
    "Greco-Bactrian Kingdom": "Indo-Greek Kingdom",
    "Shunga Empire": "Shunga/Kanva India",
  },
  "-44_-27": {
    "Roman Republic": "Roman Empire",
    "Ptolemaic Kingdom": "Roman Empire",
    "Xiongnu (weakening)": "Xiongnu (split)",
    "Indo-Greek Kingdom": "Indo-Scythian Kingdom",
    "Shunga/Kanva India": "Shunga/Kanva",
  },
  "-27_50": {
    "Yuezhi": "Kushan Empire",
    "Western Han Dynasty": "Eastern Han Dynasty",
    "Xiongnu (split)": ["Xiongnu (Northern)", "Xiongnu (Southern - Han vassal)"],
    "Indo-Scythian Kingdom": "Kushan Empire",
    "Shunga/Kanva": "Kushan Empire",
  },
  "50_117": {
    "Kingdom of Armenia": "Roman Empire",
    "Kingdom of Pontus": "Roman Empire",
    "Nabataeans": "Roman Empire",
    "Xiongnu (Northern)": "Northern Xiongnu",
    "Xiongnu (Southern - Han vassal)": "Yayoi Japan (proto-states)",
  },
  "117_200": {
    "Eastern Han Dynasty": "Eastern Han Dynasty (late)",
    "Northern Xiongnu": "Satavahana Empire",
    "Kushan Empire": "Kushan Empire (declining)",
    "Yayoi Japan (proto-states)": "Yayoi Japan",
  },
  "200_250": {
    "Parthian Empire": "Sasanian Empire",
    "Kushan Empire": "Western Kushans",
    "Goths": "Gothia",
    "Eastern Han Dynasty (late)": ["Wei Kingdom", "Shu Kingdom", "Wu Kingdom"],
    "Kushan Empire (declining)": "Kushan (remnant)",
    "Satavahana Empire": "Gupta Empire (emerging)",
    "Yayoi Japan": "Yayoi/Early Yamato Japan",
  },
  "250_300": {
    "Indo-Scythians": "Indo-Sasanian Empire",
    "Western Kushans": "Indo-Sasanian Empire",
    "Wei Kingdom": "Western Jin Dynasty",
    "Shu Kingdom": "Western Jin Dynasty",
    "Wu Kingdom": "Western Jin Dynasty",
    "Kushan (remnant)": "Kushan (declining)",
    "Gupta Empire (emerging)": "Gupta Empire",
    "Yayoi/Early Yamato Japan": "Yamato Kingdom",
  },
  "300_350": {
    "Kingdom of Kush": "Nobatia",
    "Western Jin Dynasty": ["Eastern Jin Dynasty", "Sixteen Kingdoms (Northern China)"],
    "Kushan (declining)": "Gupta Empire",
  },
  "350_395": {
    "Roman Empire": ["Western Roman Empire", "Eastern Roman Empire"],
    "Gothia": "Kidarites",
    "Indo-Sasanian Empire": "Xionites",
    "Sixteen Kingdoms (Northern China)": "Northern Wei (early)",
    "Gupta Empire": "Gupta Empire (peak)",
  },
  "395_476": {
    "Western Roman Empire": "Visigothic Kingdom",
    "Huns": "Ostrogoths",
    "Vandals": "Vandal Kingdom",
    "Xionites": "White Huns",
    "Eastern Jin Dynasty": "Liu Song Dynasty",
    "Northern Wei (early)": "Northern Wei Dynasty",
    "Gupta Empire (peak)": "Gupta Empire (declining)",
  },
  "476_530": {
    "Ostrogoths": "Ostrogothic Kingdom",
    "Ripuarian Franks": "Kingdom of the Franks",
    "Salian Franks": "Kingdom of the Franks",
    "Kingdom of Alamannia": "Kingdom of the Franks",
    "Kingdom of Soissons": "Kingdom of the Franks",
    "Northern Wei Dynasty": "Eastern Wei Dynasty",
    "Liu Song Dynasty": "Liang Dynasty",
    "Gupta Empire (declining)": "Post-Gupta Kingdoms",
    "Yamato Kingdom": "Yamato / Asuka Japan",
  },
  "530_570": {
    "Ostrogothic Kingdom": "Eastern Roman Empire",
    "Vandal Kingdom": "Eastern Roman Empire",
    "Anglo-Saxon England": "Kingdom of Mercia",
    "White Huns": "Göktürk Khaganate",
    "Kingdom of the Gepids": "Avar Khaganate",
    "Caucasian Iberia": "Georgia",
    "Himyarite Kingdom": "Eastern Roman Empire",
    "Eastern Wei Dynasty": ["Northern Zhou Dynasty", "Northern Qi Dynasty"],
    "Liang Dynasty": "Chen Dynasty",
    "Post-Gupta Kingdoms": "Göktürk Khaganate",
    "Yamato / Asuka Japan": "Asuka Japan",
  },
  "570_632": {
    "Georgia": "Khazaria",
    "Göktürk Khaganate": "Western Göktürks",
    "Kingdom of Wessex": "Kingdom of Northumbria",
    "Kingdom of Deira": "Kingdom of Northumbria",
    "Kingdom of Bernicia": "Kingdom of Northumbria",
    "Kingdom of the Suebi": "Visigothic Kingdom",
    "Northern Zhou Dynasty": "Tang Dynasty",
    "Northern Qi Dynasty": "Tang Dynasty",
    "Chen Dynasty": "Tang Dynasty",
    "Silla Kingdom": "Silla Kingdom (Unified Silla forming)",
  },
  "632_680": {
    "Eastern Roman Empire": "Byzantine Empire",
    "Sasanian Empire": "Umayyad Caliphate",
    "Lakhmid Kingdom": "Umayyad Caliphate",
    "Ghassanids": "Umayyad Caliphate",
    "Nobatia": "Umayyad Caliphate",
    "Western Göktürks": "Turks",
    "Göktürk Khaganate (fragmented)": "Tibetan Empire",
    "Goguryeo Kingdom": "Unified Silla",
    "Baekje Kingdom": "Unified Silla",
    "Silla Kingdom (Unified Silla forming)": "Unified Silla",
    "Asuka Japan": "Nara Japan (emerging)",
    "Harsha's Empire": "Pala Empire",
  },
  "680_750": {
    "Visigothic Kingdom": "Umayyad Caliphate",
    "Old Great Bulgaria": "First Bulgarian Empire",
    "Frisia Kingdom": "Kingdom of the Franks",
    "Carantania": "Kingdom of the Franks",
    "Nara Japan (emerging)": "Nara Japan",
  },
  "750_850": {
    "Umayyad Caliphate": "Emirate of Córdoba",
    "Kingdom of the Franks": ["East Franks", "West Franks", "Middle Franks"],
    "Kingdom of Italy": "East Franks",
    "Avar Khaganate": "Magyars",
    "Kingdom of Axum": "Ghana Empire",
    "Tang Dynasty": "Tang Dynasty (late/fragmenting)",
    "Tibetan Empire": "Tibetan Empire (declining)",
    "Nara Japan": "Heian Japan",
    "Pala Empire": "Pala Empire (declining)",
    "Rashtrakuta Empire": "Chola Empire",
  },
  "850_900": {
    "Kingdom of Mercia": "Viking City-States",
    "Kingdom of Northumbria": "Viking City-States",
    "Middle Franks": "Kingdom of Lower Burgundy",
    "Kingdom of Wessex": "Kievan Rus\\'",
    "Turk Shahis": "Samanid Empire",
    "Volga Bulgaria": "Principality of Hungary",
    "Tang Dynasty (late/fragmenting)": "Five Dynasties & Ten Kingdoms",
    "Tibetan Empire (declining)": "Khitan Liao Empire",
    "Nanzhao Kingdom": "Goryeo Kingdom",
    "Unified Silla": "Goryeo Kingdom",
    "Pala Empire (declining)": "Chola Empire",
  },
  "900_1000": {
    "Abbasid Caliphate": "Fatimid Caliphate",
    "East Franks": "Holy Roman Empire",
    "West Franks": "Kingdom of England",
    "Emirate of Córdoba": "Caliphate of Córdoba",
    "Principality of Hungary": "Kingdom of Hungary",
    "Kingdom of Asturias": "Kingdom of León",
    "Khazaria": "Kievan Rus\\'",
    "Viking City-States": "Duchy of Bohemia",
    "Samanid Empire": "Ghaznavid Empire",
    "Five Dynasties & Ten Kingdoms": "Northern Song Dynasty",
  },
  "1000_1071": {
    "Seljuk Dynasty": "Great Seljuk Empire",
    "Kievan Rus\\'": "Principality of Kiev",
    "Kingdom of León": "Kingdom of Galicia",
    "Caliphate of Córdoba": "Almoravid Dynasty",
    "Oghuz Turks": "Great Seljuk Empire",
    "First Bulgarian Empire": "Byzantine Empire",
    "Chola Empire": "Chola Empire (declining)",
  },
  "1071_1100": {
    "Kingdom of England": "Norman England",
    "Kingdom of Galicia": "Kingdom of Castile",
    "Khitan Liao Empire": "Jurchen Jin Empire (early)",
    "Chola Empire (declining)": "Khmer Empire",
  },
  "1100_1200": {
    "Norman England": "Angevin Empire",
    "Fatimid Caliphate": "Ayyubid Sultanate",
    "Almoravid Dynasty": "Almohad Caliphate",
    "Principality of Kiev": "Principality of Halych",
    "Kingdom of Poland": "Duchy of Sandomierz",
    "Northern Song Dynasty": "Southern Song Dynasty",
    "Jurchen Jin Empire (early)": "Jurchen Jin Dynasty",
    "Heian Japan": "Kamakura Japan",
    "Khmer Empire": "Khmer Empire",
  },
  "1200_1300": {
    "Ayyubid Sultanate": "Mamluk Sultanate",
    "Angevin Empire": "Kingdom of England",
    "Khwarezmid Dynasty": "Golden Horde",
    "Kimek-Kipchak confederation": "Golden Horde",
    "Great Seljuk Empire": "Ilkhanate",
    "Kara-Khitans": "Chagatai Khanate",
    "Holy Roman Empire": "Holy Roman Empire Minor States",
    "Sultanate of Rum": "Byzantine Empire",
    "Ghurid Dynasty": "Ilkhanate",
    "Kingdom of Castile": "Crown of Castile",
    "Ghana Empire": "Mali Empire",
    "Kingdom of Denmark": "Kingdom of France",
    "Southern Song Dynasty": "Yuan Dynasty",
    "Jurchen Jin Dynasty": "Yuan Dynasty",
    "Xi Xia Kingdom": "Yuan Dynasty",
    "Mongol Empire (early)": ["Yuan Dynasty", "Chagatai Khanate", "Golden Horde (eastern territories)"],
    "Goryeo Kingdom": "Goryeo Kingdom (Mongol vassal)",
    "Khmer Empire": "Sukhothai Kingdom",
    "Delhi Sultanate (early)": "Delhi Sultanate",
  },
  "1300_1350": {
    "Ilkhanate": "Jalayirid Sultanate",
    "Almohad Caliphate": "Marinid Sultanate",
    "Galicia-Volhynia": "Grand Duchy of Lithuania",
    "Principality of Smolensk": "Grand Duchy of Lithuania",
    "Yuan Dynasty": "Ming Dynasty (early)",
    "Chagatai Khanate": "Chagatai Khanate (fragmenting)",
    "Golden Horde (eastern territories)": "Yuan Dynasty (remnant)",
    "Goryeo Kingdom (Mongol vassal)": "Goryeo Kingdom",
    "Kamakura Japan": "Muromachi Japan",
    "Sukhothai Kingdom": "Majapahit Empire",
    "Delhi Sultanate": "Delhi Sultanate / Bahmani",
  },
  "1350_1453": {
    "Byzantine Empire": "Ottoman Empire",
    "Chagatai Khanate": "Timurid Empire",
    "Jalayirid Sultanate": "Timurid Empire",
    "Kingdom of Hungary": "House of Jagiellon",
    "Kingdom of Bohemia": "House of Habsburg",
    "Grand Duchy of Lithuania": "House of Jagiellon",
    "Makuria": "Makuria Kingdom",
    "Ming Dynasty (early)": "Ming Dynasty",
    "Yuan Dynasty (remnant)": "Timurid Remnants",
    "Chagatai Khanate (fragmenting)": "Timurid Remnants",
    "Goryeo Kingdom": "Joseon Korea",
    "Majapahit Empire": "Majapahit Empire (declining)",
    "Delhi Sultanate / Bahmani": "Delhi Sultanate / Bahmani",
  },
};
